language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "been-there-stackathon-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: been-there-stackathon
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: kcJo2S3RiE5G5H3ulg2wwUFk9jGUr5++/3EbR/qS4H4NRd11OZH8NhjMvwLMebVxHg7Q9/1CO6AV/3OaWqQADHUMaMGDN99++5LM8c5tVg/x0iy7OzCsxxZvYvU4BQO+MyUvozCxiZAZrZ6xpAAUqN6NiV7GBYCU2lg23hdIMWikT3Tf812piCUORe7oEqkWQsCRlAmFnfF5E176jTa4Iw4lmoJj6pfbdVUcdgOJUyBSneABQjgrS7E8WD9Ei5CF25yWWIbBI13s0r0RQ5xilvaoIkSNwpM/m9gWVNRHwlLiGKwG3YZpvDylD7fIZzBd3Jg+bcknH2xBZsIAUPYy7UVlHWzwMUiwBsDX1agQwODrKG+Kul20U5fRNLRyhN4rmJWsUb6LWi+M8mq2kYJ9O2x8eRK7ZNWzfZSapwKVbpv0dw1jHUhvwvbTB8kAh8toy8e+u7NxmATAwySzoJ8a1pvAOHzIf5/Kk62sQ4D2+7yOFvCiqVDmZQenNoOO2hLIm79IOEeDoCpKp8AXXTK71Q3sAFNxpWzk8LfwxqBx66e3wvrY+KzyOSm8mtUdOKAh6oiTD6hop6h2d1B5mmaeFtOv59QyFTHH/VAs40WGvA9YR0uEo1RnVcrHFR8pzpTvXSg+Zf88U/Voh6lwWEzRaxN2MRNOkAosbz3tK9TvaLc=
