language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "stackathon-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: been-there-stackathon
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: vepVkCn8J4+JhJ1ZiI61TY9UXFUSAOeqby+C/NpYkZRtpjUtB3wo9D+Ylx5zRsOj0MZ4KWIbEGUqbnjia3L9H+kl9v37m33OnKUF+87nmnEEUOMEw1QbJlm2umWO5ZGq2gqPsttpabt2FxMeElV0PgRFUgUuG+MOUCpWGx/gExPweeXArNpufTNUr0fOTjBXPaiSHIRxb29X3ILx4BS3JlDIFV1Te0NuyEnUYhLeBIWRo+3+wK7wqEP2np2h23BqhZq7s2vgs36TsmG3hjlmgb138RWhm0AfdLwGBd854VJg2aKbMLq8JWE/iXJk1PU/HLJWCCwWB1mklklpOOrFt8a9xptl/ycuhiAexyEAE1b/1gDdtd0QqP9GDcVJZ2BqD/SGMJan1kiVbwGcZseRep0Vqo/eEzN09EUS2OBMZQ/dOghz2kmalq48qTKV5EXCbCwM3qG1j1pPwqJSitUjN7uEaDzUp8JXNEwEpPglzTiTXfjg9gQRW5KQtbPC2nj5RVYRZkDQpQVRf8ER/uRmPuL+5vqr+1xmFFXI7Ap3YJwJ1Han9ihJlIXhmp+5xd0AoaG1OGVlhrdTPKcWcVj96Sps4hv/Nq5tYz+bNzT3QNbFKmR4ff3ItvHRz1JyHGxEg24z6qLwO8Exrpb6o/+3T9z3h83t23yDo8yAbrX5vhY=
