language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "been-there-stackathon-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the buil
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: been-there-stackathon
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: u4x1vZmO5WnlQLA6RWjLGyJTrV68OqylA/iL8GMvGKBnY5qlNJFD5Zqv75KTS425Z8LvZQuPg675hpEKw/7GYpBz8xascSmYVExeDYIxCUmNTYb6hChWylb/5vQWkdU3GsdYmuUFvskH2RxvbIcgU9dESwvUqfEuqqMunDAW89lY2XDNb1J3nMWKwpX/nppLEBOk9JBN99XWYmNRdZxZMvZgBCpn2dGFGNyUU5qc/xfjSAGxeaADFo4sYDVWHfpfDP2a2Yk/sVesuTne/WsQsLmvFbdTxbpfXsPfclTEQBmKEtLR1RALxvZcMaYDbfTShuxRs6QZKMv1aHu2Rpcgh4MTo1AW1rcaLS6uU6eENtiowMLUDipPvDuQ4yON8v9gqByM/KtgIBszRp52YjsJF0PO/z/P6eKEUQPLgbXOhLUqG5QzAnVwrmn/OsdUbktbjuTt02HimH8qVlsGfLU/LT1r9khJdlR9QLYa+3bbbcnDKiOydSfFbdm1mtrjz91uquvWvbZP/pkLOQNdiAkkvaNJmBTTtgAKxfuEUECtUqOaXJUhKRYhEaStWHkX9m504B33uiFtyX8zVaxdeJ3NX3naQFhA0QnMJSE/1W5RxTFmvrRR6ZnHZdrQ6BZYQUVHh3xk7mmH2CLaQ3fXbQFaMDAOHxer3VExMH449/G+5tM=
